select inst_id,name,BLOCK_SIZE, PHYSICAL_READS, DB_BLOCK_GETS, CONSISTENT_GETS, 1 - (PHYSICAL_READS / (DB_BLOCK_GETS + CONSISTENT_GETS)) "Hit Ratio"
  FROM gv$BUFFER_POOL_STATISTICS
ORDER BY 1,2;

SELECT NAME, BLOCK_SIZE, SUM(BUFFERS)
  FROM V$BUFFER_POOL
 GROUP BY NAME, BLOCK_SIZE
 HAVING SUM(BUFFERS) > 0;
 
 
 
 SELECT NAME, BLOCK_SIZE, SUM(BUFFERS), round((sum(buffers)*BLOCK_SIZE)/1024/1024,0) as MBs
  FROM V$BUFFER_POOL
 GROUP BY NAME, BLOCK_SIZE
 HAVING SUM(BUFFERS) > 0;